app:tests:
  - changed-files:
      - any-glob-to-any-file: 'tests/**'

benchmarks:
  - changed-files:
      - any-glob-to-any-file: 'benches/**'

examples:
  - changed-files:
      - any-glob-to-any-file: 'examples/**'

docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'
      - any-glob-to-any-file: '*.md'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

cargo:
  - changed-files:
      - any-glob-to-any-file: 'Cargo.toml'
      - any-glob-to-any-file: 'Cargo.lock'
      - any-glob-to-any-file: '**/Cargo.toml'
      - any-glob-to-any-file: '**/Cargo.lock'

security:
  - changed-files:
      - any-glob-to-any-file: 'SECURITY.md'
      - any-glob-to-any-file: '.github/security/**'

release:
  - changed-files:
      - any-glob-to-any-file: 'CHANGELOG.md'
      - any-glob-to-any-file: '**/CHANGELOG.md'

tooling:
  - changed-files:
      - any-glob-to-any-file: 'deny.toml'
      - any-glob-to-any-file: 'spellcheck.toml'
      - any-glob-to-any-file: 'spellcheck.dic'
      - any-glob-to-any-file: '.editorconfig'
      - any-glob-to-any-file: '**/.cargo/**'

crates:api:
  - changed-files:
      - any-glob-to-any-file: 'crates/api/**'

crates:string:
  - changed-files:
      - any-glob-to-any-file: 'crates/string/**'

crates:web:
  - changed-files:
      - any-glob-to-any-file: 'crates/web/**'
