# Basics

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

benchmarks:
  - changed-files:
      - any-glob-to-any-file:
          - 'benches/**'

examples:
  - changed-files:
      - any-glob-to-any-file:
          - 'examples/**'

fuzz:
  - changed-files:
      - any-glob-to-any-file:
          - 'fuzz/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - 'README.md'
          - 'CONTRIBUTING.md'
          - 'CODE_OF_CONDUCT.md'
          - 'SUPPORT.md'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

cargo:
  - changed-files:
      - any-glob-to-any-file:
          - 'Cargo.toml'
          - 'Cargo.lock'
          - '**/Cargo.toml'
          - '**/Cargo.lock'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'SECURITY.md'
          - '.github/security/**'

release:
  - changed-files:
      - any-glob-to-any-file:
          - 'CHANGELOG.md'
          - '**/CHANGELOG.md'

tooling:
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**'
          - '**/.cargo/**'
          - '.editorconfig'
          - '.taplo.toml'
          - '.rustfmt.toml'
          - '.clippy.toml'
          - 'deny.toml'
          - 'spellcheck.toml'
          - 'spellcheck.dic'
          - 'rust-toolchain'
          - 'rust-toolchain.toml'
          - 'package.json'
          - 'package-lock.json'
          - 'npm-shrinkwrap.json'
          - '.node-version'

# Crates

crates:demo:
  - changed-files:
      - any-glob-to-any-file:
          - 'crates/demo/**'
