# Basics

- name: 'triage'
  color: 'FBCA04'
  description: 'Needs initial review / classification'

- name: 'bug'
  color: 'D73A4A'
  description: 'Something is not working'

- name: 'enhancement'
  color: 'A2EEEF'
  description: 'New feature or improvement request'

- name: 'tests'
  color: '5319E7'
  description: 'Changes in tests'

- name: 'benchmarks'
  color: 'FBCA04'
  description: 'Benchmarks / performance related'

- name: 'examples'
  color: 'D4C5F9'
  description: 'Examples updates'

- name: 'fuzz'
  color: '6F42C1'
  description: 'Fuzz updates'

- name: 'docs'
  color: '0075CA'
  description: 'Documentation updates'

- name: 'ci'
  color: '1D76DB'
  description: 'CI / GitHub automation changes'

- name: 'cargo'
  color: 'C2E0C6'
  description: 'Cargo manifests / lockfiles changes'

- name: 'security'
  color: 'D73A4A'
  description: 'Security policy / advisories'

- name: 'release'
  color: 'B60205'
  description: 'Changelog / release tracking'

- name: 'tooling'
  color: 'BFDADC'
  description: 'Dev tooling, scripts, and repo configs'

# Crates

- name: 'crates:api'
  color: '0E8A16'
  description: 'Changes in crates/api'

- name: 'crates:string'
  color: '0E8A16'
  description: 'Changes in crates/string'

- name: 'crates:web'
  color: '0E8A16'
  description: 'Changes in crates/web'
