printWidth: 100
tabWidth: 2
useTabs: false

semi: true
singleQuote: true
jsxSingleQuote: true
quoteProps: as-needed

trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always

endOfLine: lf
proseWrap: preserve
singleAttributePerLine: false
embeddedLanguageFormatting: auto

overrides:
  - files: ['*.yml', '*.yaml']
    options:
      tabWidth: 2

  - files: ['*.md', '*.mdx']
    options:
      embeddedLanguageFormatting: off
