printWidth: 100
tabWidth: 4
useTabs: false

semi: true
singleQuote: true
quoteProps: as-needed

trailingComma: all
bracketSpacing: true
arrowParens: always

endOfLine: lf
proseWrap: always

overrides:
  - files: ['*.yml', '*.yaml']
    options:
      tabWidth: 2

  - files: '*.md'
    options:
      printWidth: 100
